import { useEffect, useRef, useState, useMemo } from "react";
import L from "leaflet";
import "leaflet/dist/leaflet.css";
type Ponto = any;
export default function Painel() {
  const mapRef = useRef<L.Map | null>(null); const mapDiv = useRef<HTMLDivElement>(null);
  const [pontos, setPontos] = useState<Ponto[]>(() => { const s = localStorage.getItem("geoclima_final_v3"); if (s) { try { return JSON.parse(s).map((p:any)=> ({...p, status: p.status || "Pendente", data: p.quando || "Agora"})); } catch {} } return []; });
  const [sel, setSel] = useState<Ponto | null>(null);
  const [filtroFoto, setFiltroFoto] = useState<"todas"|"comFoto">("todas");
  const filtrados = useMemo(()=> filtroFoto==="comFoto" ? pontos.filter((p:any)=>p.foto) : pontos, [pontos, filtroFoto]);
  useEffect(()=>{ if(!mapDiv.current || mapRef.current) return; const map = L.map(mapDiv.current,{zoomControl:false}).setView([-23.433,-45.084],13); mapRef.current=map; L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'OSM',maxZoom:19}).addTo(map); L.control.zoom({position:'bottomright'}).addTo(map); return()=>{ map.remove(); mapRef.current=null; } },[]);
  useEffect(()=>{ if(!mapRef.current) return; mapRef.current.eachLayer((l:any)=>{ if(l instanceof L.Marker) mapRef.current?.removeLayer(l); }); filtrados.forEach((p:any)=>{ const color = p.statusRua==="Interditada" ? "#ef4444" : p.freq==="Alta" ? "#ef4444" : "#eab308"; const icon = L.divIcon({ html:`<div style="background:${color};width:30px;height:30px;border-radius:50%;border:3px solid white;display:flex;align-items:center;justify-content:center">${p.tipo.emoji}</div>`, iconSize:[30,30], iconAnchor:[15,15], className:"" }); const m = L.marker([p.lat,p.lng],{icon} as any).addTo(mapRef.current!); m.on('click',()=>setSel(p)); }); },[filtrados]);
  const validar = (id:number)=>{ const upd = pontos.map((p:any)=>p.id===id ? {...p, status: "Validado CEMADEN"} : p); setPontos(upd); localStorage.setItem("geoclima_final_v3", JSON.stringify(upd)); };
  const exportCSV = () => { const h="id,bairro,rua,simples,tecnico,categoria,causa,freq,qtd,status,data,lat,lng,tem_foto,obs"; const rows = filtrados.map((p:any)=>`${p.id},"${p.bairro}","${p.rua}","${p.tipo.simples}","${p.tipo.tecnico}","${p.tipo.categoria}","${p.tipo.risco}","${p.freq}",${p.qtd},"${p.status}",${p.data},${p.lat},${p.lng},${p.foto?"SIM":"NAO"},"${p.obs||""}"`).join("\n"); const blob = new Blob([h+"\n"+rows],{type:"text/csv"}); const url = URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download=`cemaden-fotos-${new Date().toISOString().slice(0,10)}.csv`; a.click(); };
  return (
    <div className="min-h-screen bg-[#0f172a] text-white font-sans text-[13px]">
      <div className="bg-amber-400 text-black text-[11px] py-1.5 overflow-hidden whitespace-nowrap font-bold"><div className="flex gap-8 animate-[marquee_30s_linear_infinite]"><span>PAINEL CEMADEN - 17 TIPOS CAUSAS NATURAIS + FOTOS + ACESSIBILIDADE - </span><span>Fotos aparecem aqui - </span></div></div>
      <style>{`@keyframes marquee{0%{transform:translateX(0)}100%{transform:translateX(-50%)}}`}</style>
      <header className="border-b border-slate-700 px-4 py-3 flex justify-between items-center"><div className="flex items-center gap-3"><div className="bg-white text-black w-8 h-8 rounded flex items-center justify-center font-black text-[11px]">GC</div><div><div className="font-black">GEOCLIMA VALE - PAINEL CEMADEN - FOTOS</div><div className="text-[11px] text-slate-400">Validacao com foto - {filtrados.length} pontos - {filtrados.filter((p:any)=>p.foto).length} com foto</div></div></div><div className="flex gap-2"><button onClick={()=>setFiltroFoto(f=>f==="todas"?"comFoto":"todas")} className={`px-3 py-1.5 rounded-full text-[11px] font-bold ${filtroFoto==="comFoto"?"bg-yellow-300 text-black":"bg-slate-700 text-white"}`}>{filtroFoto==="comFoto"?"So com foto":"Todas"}</button><a href="/" className="bg-white text-black px-3 py-1.5 rounded-full text-[11px] font-bold">Morador</a><button onClick={exportCSV} className="bg-emerald-500 text-white px-4 py-1.5 rounded-full text-[11px] font-black">Export CSV</button></div></header>
      <div className="px-4 py-3 grid grid-cols-1 lg:grid-cols-[1fr_420px] gap-4">
        <div className="bg-white text-black rounded-xl overflow-hidden"><div className="p-3 border-b bg-gray-50 text-[10px] font-black text-gray-500 flex justify-between"><span>TABELA COM FOTO VISIVEL</span><span>{filtrados.filter((p:any)=>p.foto).length} com foto</span></div><div className="overflow-auto max-h-[700px]"><table className="w-full text-[11px]"><thead className="bg-gray-100 text-[10px] font-black text-gray-500 sticky top-0"><tr><th className="text-left p-2">LOCAL + FOTO</th><th className="text-left p-2">TIPO (17)</th><th className="text-left p-2">FREQ</th><th className="p-2">ACAO</th></tr></thead><tbody>{filtrados.map((p:any)=>(<tr key={p.id} className="border-t hover:bg-gray-50"><td className="p-2"><div className="font-bold">{p.bairro} - {p.rua}</div><div className="text-[10px] text-gray-400">{p.data} - {p.statusRua}</div>{p.foto ? <img src={p.foto} alt={`Foto ${p.rua}`} className="w-32 h-20 object-cover rounded-lg mt-1 border" /> : <div className="text-[10px] text-red-500">Sem foto</div>}</td><td className="p-2"><div className="font-bold">{p.tipo.emoji} {p.tipo.simples}</div><div className="bg-black text-white text-[9px] px-2 py-0.5 rounded-full inline-block mt-1">{p.tipo.tecnico}</div><div className="text-[9px] text-gray-500 mt-1">{p.tipo.categoria} - {p.tipo.risco}</div><div className="text-[9px] mt-1">{p.obs}</div></td><td className="p-2"><span className={`px-2 py-1 rounded-full text-white font-bold text-[10px] ${p.freq==="Alta"?"bg-red-500":p.freq==="Média"?"bg-orange-500":"bg-yellow-500"}`}>{p.freq} - {p.qtd}</span></td><td className="p-2"><div className="flex flex-col gap-1"><button onClick={()=>validar(p.id)} className="bg-emerald-600 text-white px-3 py-1 rounded-full text-[10px] font-bold">Validar</button><button onClick={()=>{setSel(p); mapRef.current?.setView([p.lat,p.lng],15);}} className="border px-3 py-1 rounded-full text-[10px] font-bold">Mapa</button></div></td></tr>))}</tbody></table></div></div>
        <div className="space-y-3"><div className="bg-white rounded-xl overflow-hidden border"><div className="bg-slate-800 text-white px-3 py-2 text-[11px] font-black">MAPA TECNICO - 17 TIPOS + FOTOS</div><div ref={mapDiv} className="w-full h-[340px] bg-gray-200" /></div>{sel && (<div className="bg-white text-black rounded-xl p-4"><h4 className="font-black text-[11px]">DETALHE COM FOTO</h4><div className="mt-2"><div className="font-bold">{sel.bairro} - {sel.rua}</div>{sel.foto && <img src={sel.foto} alt={`Foto grande ${sel.rua}`} className="w-full h-56 object-cover rounded-xl mt-2 border" />}<div className="mt-2 text-[11px]">{sel.tipo.emoji} {sel.tipo.simples} - <span className="bg-black text-white px-2 py-0.5 rounded-full">{sel.tipo.tecnico}</span></div><div className="text-[10px] text-gray-500 mt-1">{sel.tipo.categoria} - Causa: {sel.tipo.risco}</div></div></div>)}<div className="bg-slate-800 border border-slate-700 rounded-xl p-4 text-[11px] text-slate-300"><h4 className="font-black text-white mb-2">ACESSIBILIDADE</h4><ul className="list-disc pl-4 space-y-1"><li>A+ / A fonte 100-150%</li><li>Alto contraste</li><li>Tab + Enter navega</li><li>Leitor tela: aria-label, alt fotos</li><li>Focus azul 3px</li></ul></div></div>
      </div>
    </div>
  );
}
